version: '3'
services:
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile 
    image: shaspitz/geth-poa:v0
    environment:
      - GETH_NODE_TYPE=bootnode
      - BOOT_KEY=7b548c1c0fbe80ef1eb0aaec2edf26fd20fb0d758e94948cf6c5f2a486e735f6
    networks:
      poa_net:
        ipv4_address: '172.13.0.100'
    ports:
      - 8545:8545
    volumes:
      - geth-data-bootnode:/data
  node1:
    build: 
      context: .
      dockerfile: Dockerfile
    image: shaspitz/geth-poa:v0
    environment:
      - GETH_NODE_TYPE=signer
      - BLOCK_SIGNER_ADDRESS=0xd9cd8E5DE6d55f796D980B818D350C0746C25b97
      - BLOCK_SIGNER_PRIVATE_KEY=${NODE1_PRIVATE_KEY}
    networks:
      poa_net:
        ipv4_address: '172.13.0.2'
    volumes:
      - geth-data-node1:/data
  node2:
    build: 
      context: .
      dockerfile: Dockerfile
    image: shaspitz/geth-poa:v0
    environment:
      - GETH_NODE_TYPE=signer
      - BLOCK_SIGNER_ADDRESS=0x788EBABe5c3dD422Ef92Ca6714A69e2eabcE1Ee4
      - BLOCK_SIGNER_PRIVATE_KEY=${NODE2_PRIVATE_KEY}
    networks:
      poa_net:
        ipv4_address: '172.13.0.3'
    volumes:
      - geth-data-node2:/data

networks:
  poa_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16

volumes:
  geth-data-bootnode:
  geth-data-node1:
  geth-data-node2:
